public sealed class SynergyRule
{
    public string Id { get; set; } = "";

    // Traits required for this synergy to trigger
    public List<string> RequiredTraits { get; set; } = new();

    // Risks required for this synergy to trigger
    public List<string> RequiredRisks { get; set; } = new();

    // Positive or negative modifier
    // Example: +10 for good synergy, -20 for dangerous conflict
    public int Modifier { get; set; }

    // Trait or effect created by this synergy
    public string ResultTrait { get; set; } = "";

    // Optional description for UI/debug output
    public string Description { get; set; } = "";

    // Optional risk generated by this synergy
    public string? AddedRisk { get; set; }

    public int AddedRiskStrength { get; set; }
}
